[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Configuración de redirecciones para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proxy para API local
[[redirects]]
  from = "/api/*"
  to = "http://localhost:5000/api/:splat"
  status = 200